name: Code Quality

# Trigger the workflow on push events.
on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Run Tests
        run: |
{%- if cookiecutter.testing == "TDD" %}
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
{%- elif cookiecutter.testing == "BDD" %}
          behave --junit --junit-directory junit
{%- endif %}

      - name: Lint with Ruff
        run: |
          ruff --output-format=github .
        continue-on-error: true
