# https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html#github-actions
name: Semantic Release
run-name: Versioning and Releasing 🚀

on:
  push:
    branches:
      - {{cookiecutter.main_branch}}

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Python Semantic Release
        # https://github.com/python-semantic-release/python-semantic-release/blob/master/action.yml
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
